### PR TITLE
8 Tiefling Names

### PR DESCRIPTION
**Pull request by HedgehogHolly**
### Changes made:

- added female Tiefling names
- added male Tiefling names
- added Tiefling surnames
- updated my branch with master to add Gnome and Hafling names

🎲

### CODE REVIEW

**Comment by KingFruit85** [comment]
@HedgehogHolly 

So I have been a bit naughty and I added a handfull of names for each race lastnight and didn't update the tickets 👎

Looking over your changes there is now duplication of the following variables:

**const maleTieflingNames
const femaleTieflingNames
const tieflingSurnames**

Can you merge the lists? I will be happy to accept then 😁

**Comment by HedgehogHolly** [comment]
Silly Chris! 😛 I've merged the names now

**Review by KingFruit85 — APPROVED** [review]
@HedgehogHolly 

Awesome, happy for you to merge :)

thanks and sorry! 🧙‍♂️

**Comment by KingFruit85** [comment]
🎉🎉🎉

**Pull request merged**
